# Site settings
title: Regina Sánchez
email:
description: Some girls are made of adventure, fine beer, brains, and no fear.
baseurl: "" # the subpath of your site, e.g. /blog

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/RegiSanchez
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
